import type { Abi } from "viem";

// this file is copied from smart contract artifact generated by hardhat compile step.
// It is used to provide the ABI for contract interaction in the frontend.
// If the contract ABI changes, this file should be updated accordingly.
// import SimpleTexasHoldemArtifact from "./SimpleTexasHoldem.json";

// export const SIMPLE_TEXAS_HOLDEM_ABI: Abi = SimpleTexasHoldemArtifact.abi as Abi;



import { simpleTexasHoldemAbi } from "./wagmi-generated";
export const SIMPLE_TEXAS_HOLDEM_ABI: Abi = simpleTexasHoldemAbi as Abi;